### ISSUE TITLE
Not able to create new app, no chains available

### ISSUE THREAD

**Issue by nymd** [pokt-foundation/portal-frontend#134]
Attempting to create an app is unsuccessful as there are no chains available.

**To Reproduce**
1. Login
2. Create new app
3. See that there are no chains and button is greyed out

![image](https://user-images.githubusercontent.com/16605170/120824875-b2cda380-c50d-11eb-821a-bf45fb30c255.png)

**Desktop (please complete the following information):**
 - All browsers

Logs show multiple errors like 
> (node:52) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'freeTierApplicationAccount' of undefined

**Comment by Evalir** [comment]
After some manual fiddling with the app pool DB and a few PRs on the `portal` repo, this has been fixed. For posteriority, here's a quick writeup:

This was a situation that was completely expected with the current (very lean and not very able to recover itself from chain failures) architecture of the workers. While they're resilient to changing block times due to consistent polling, the combination of the chain halt along with several releases of PocketJS made the workers fail in critical sections regarding sending/staking POKT. The fix was just to upgrade, and then use some of the apps so the worker pool had exactly the right size for it to continue working normally.

Once @rem1niscence gets onboarded onto the portal, we'll be looking at strengthening the infrastructure around these workers so that they're able to at least recover from failure much more gracefully, mainly by polling the on-chain status of TXs sent and whatnot.
